<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>MAIA</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    </head>
    <body >
<div class='container-fluid'>
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand">MAIA - MAIs uma Agenda</a>
    </div>
    <ul class="nav navbar-nav">
      <li class="active"><a href="/">Início</a></li>
      <li>               <a href="/tarefa/todas">Todas as Tarefas</a></li>
      <li>               <a href="/tarefa/nova">Nova Tarefa</a></li>
      <li>               <a href="/tarefa/anotacoes">Listar anotacoes</a></li>

    </ul>
  </div>
</nav>